//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySachT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PhieuGhiNoDaiLy
    {
        public int ID { get; set; }
        public int DonGiaXuat { get; set; }
        public int SoLuongTon { get; set; }
        public int TienNo { get; set; }
        public int SoLuongDaXuat { get; set; }
        public int SoLuongBanDuoc { get; set; }
        public int MaPhieu { get; set; }
        public int MaSach { get; set; }
    
        public virtual PhieuGhiNoDaiLy PhieuGhiNoDaiLy { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
