//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySachT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaXuatBan
    {
        public NhaXuatBan()
        {
            this.PhieuNhaps = new HashSet<PhieuNhap>();
            this.PhieuYeuCauBans = new HashSet<PhieuYeuCauBan>();
            this.ThongKeChoNXBs = new HashSet<ThongKeChoNXB>();
        }
    
        public int MaNXB { get; set; }
        public string TenNXB { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
    
        public virtual ICollection<PhieuNhap> PhieuNhaps { get; set; }
        public virtual ICollection<PhieuYeuCauBan> PhieuYeuCauBans { get; set; }
        public virtual ICollection<ThongKeChoNXB> ThongKeChoNXBs { get; set; }
    }
}
