//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySachT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.PhieuNhaps = new HashSet<PhieuNhap>();
        }
    
        public int MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
    
        public virtual ICollection<PhieuNhap> PhieuNhaps { get; set; }
    }
}
